const BRAND = {
  name: "KUKA HOME",
  colors: {
    canvas: "#f6f0e8",
    surface: "#fffdf9",
    surfaceStrong: "#efe3d3",
    accent: "#b78f5a",
    accentDeep: "#8f6b41",
    text: "#171412",
    muted: "#6e6257",
    line: "rgba(23,20,18,0.08)",
  },
};

const benefits = [
  { icon: "✦", title: "Premium materiallar", text: "Tabiiy tekstura, sinovdan o'tgan qoplama va uzoq xizmat muddati." },
  { icon: "◌", title: "Zamonaviy dizayn", text: "Luxury editorial ruhidagi siluetlar va muvozanatli ranglar." },
  { icon: "⌁", title: "Qulay to'lov", text: "Moslashuvchan to'lov yechimlari va individual takliflar." },
  { icon: "➜", title: "Yetkazib berish", text: "Toshkent va hududlarga ehtiyotkor logistika hamda o'rnatish." },
  { icon: "⌂", title: "Showroom tajribasi", text: "Mahsulotni jonli ko'rish, solishtirish va maslahatchi bilan tanlash." },
  { icon: "✓", title: "Kafolat va servis", text: "Xariddan keyin ham qo'llab-quvvatlash va xizmat kafolati." },
];

const categories = [
  {
    title: "Divanlar",
    subtitle: "Statement living",
    image: "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=900&q=80",
  },
  {
    title: "Kreslolar",
    subtitle: "Soft lounge",
    image: "https://images.unsplash.com/photo-1519947486511-46149fa0a254?auto=format&fit=crop&w=900&q=80",
  },
  {
    title: "Krovatlar",
    subtitle: "Private suite",
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80",
  },
  {
    title: "Matraslar",
    subtitle: "Sleep comfort",
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80",
  },
  {
    title: "Stol va stullar",
    subtitle: "Dining lines",
    image: "https://images.unsplash.com/photo-1449247709967-d4461a6a6103?auto=format&fit=crop&w=900&q=80",
  },
  {
    title: "Saqlash mebellari",
    subtitle: "TV zone & storage",
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80",
  },
];

const products = [
  {
    name: "Monaco Sofa",
    description: "Yumshoq bukle fakturasi va chuqur o'tirish qulayligi bilan premium divan.",
    price: "38 900 000 so'm",
    image: "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=900&q=80",
  },
  {
    name: "Aster Lounge Chair",
    description: "Minimal shakl, oltin aktsent va personal reading corner uchun ideal model.",
    price: "Narxni so'rang",
    image: "https://images.unsplash.com/photo-1519947486511-46149fa0a254?auto=format&fit=crop&w=900&q=80",
  },
  {
    name: "Sienna Bed",
    description: "Headboard detailing va mat premium qoplamali zamonaviy krovat.",
    price: "47 500 000 so'm",
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80",
  },
  {
    name: "Luna Dining Set",
    description: "6 kishilik stol va chair kombinatsiyasi, showroom favoritlaridan biri.",
    price: "Narxni so'rang",
    image: "https://images.unsplash.com/photo-1449247709967-d4461a6a6103?auto=format&fit=crop&w=900&q=80",
  },
];

const featuredProducts = [
  {
    name: "Velora Console",
    note: "Accent storage with graphite detail",
    image: "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "Noma Armchair",
    note: "Compact premium silhouette",
    image: "https://images.unsplash.com/photo-1512212621149-107ffe572d2f?auto=format&fit=crop&w=800&q=80",
  },
  {
    name: "Linea Side Table",
    note: "Warm wood and stone finish",
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80",
  },
];

const showrooms = [
  {
    city: "Toshkent flagship",
    address: "Toshkent sh., Amir Temur ko'chasi, 108",
    hours: "Har kuni 10:00 - 20:00",
  },
  {
    city: "Toshkent city showroom",
    address: "Toshkent city mall, 2-qavat premium zone",
    hours: "Har kuni 11:00 - 22:00",
  },
  {
    city: "Samarqand partner space",
    address: "Universitet xiyoboni, 24A",
    hours: "Du - Sha 10:00 - 19:00",
  },
];

const testimonials = [
  {
    name: "Madina A.",
    review: "Showroomdagi konsultatsiya juda yoqdi. Divan sifati va rang tanlovi rasmdagidan ham premium ko'rinadi.",
  },
  {
    name: "Azizbek R.",
    review: "Telegram orqali tez javob berishdi, keyin showroomga borib yakuniy tanlov qildik. Servis darajasi yuqori.",
  },
  {
    name: "Dilnoza K.",
    review: "Krovat va matras kombinatsiyasi uchun aynan kerakli tavsiya berishdi. Yetkazib berish ham silliq o'tdi.",
  },
];

const translations = {
  uz: {
    "menu.home": "Bosh sahifa",
    "menu.categories": "Kategoriyalar",
    "menu.bestsellers": "Bestsellerlar",
    "menu.collection": "Yangi kolleksiya",
    "menu.promo": "Aksiya",
    "menu.about": "Biz haqimizda",
    "menu.showrooms": "Showroomlar",
    "menu.contact": "Kontakt",
    "cta.catalog": "Katalogni ko'rish",
    "cta.catalogShort": "Katalog",
    "cta.manager": "Menejer bilan bog'lanish",
    "hero.eyebrow": "Premium showroom tajribasi",
    "hero.title": "Interyeringizga mos nafis mebel kolleksiyalari",
    "hero.text": "KUKA HOME bilan har bir xona uchun premium divanlar, krovatlar va dizaynerlik yechimlarini tanlang. Showroom darajasidagi hissiyot, qulay servis va tez aloqa bir joyda.",
    "hero.stat1": "yillik tajriba",
    "hero.stat2": "mijozlar reytingi",
    "hero.stat3": "baxtli buyurtmalar",
    "hero.label": "2026 Signature Collection",
    "hero.badge": "Shaxsiy tanlov + showroom konsultatsiya",
    "benefits.eyebrow": "Nega aynan KUKA HOME",
    "benefits.title": "Premium mahsulot va servisni birlashtirgan yondashuv",
    "categories.eyebrow": "Katalog yo'nalishlari",
    "categories.title": "Har bir xona uchun tanlangan premium kolleksiyalar",
    "categories.cta": "Barchasini ko'rish",
    "products.eyebrow": "Eng ko'p tanlanayotganlar",
    "products.title": "Bestseller mahsulotlar va tezkor buyurtma yo'li",
    "featured.eyebrow": "New collection",
    "featured.title": "Yangi kolleksiya: editorial uslubdagi yashash xonalari",
    "featured.text": "Yumshoq teksturalar, chuqur rang balansi va zamonaviy siluetlar bilan yaratilgan tavsiya etilgan to'plam.",
    "featured.cta": "Kolleksiyani so'rash",
    "promo.eyebrow": "Cheklangan taklif",
    "promo.title": "Ramazon premium aksiyasi - tanlangan modellarga maxsus narx",
    "promo.text": "Showroom tashrifi yoki menejer bilan bog'lanish orqali individual chegirma, yetkazib berish va to'lov shartlarini oling.",
    "promo.days": "Kun",
    "promo.hours": "Soat",
    "promo.minutes": "Daqiqa",
    "promo.cta": "Aksiyaga ulgurish",
    "showroom.eyebrow": "Offline tajriba",
    "showroom.title": "Showroomlarimizga tashrif buyurib, kolleksiyani jonli ko'ring",
    "about.eyebrow": "Brend hikoyasi",
    "about.title": "KUKA HOME - sifat, estetika va servisni birlashtirgan premium manzil",
    "about.text1": "Biz interyerga mos, uzoq muddat xizmat qiladigan va kundalik qulaylikni oshiradigan mebellarni tanlaymiz. Har bir model showroom tajribasi, material sifati va servis qulayligi bilan saralanadi.",
    "about.text2": "Mijozga yaqin konsultatsiya, individual takliflar va post-sale qo'llab-quvvatlash KUKA HOME'ni oddiy do'kondan premium hamkor darajasiga olib chiqadi.",
    "about.point1": "material va finishing",
    "about.point2": "konsultatsiya va servis",
    "about.point3": "aloqa va buyurtma jarayoni",
    "testimonials.eyebrow": "Mijozlar ishonchi",
    "testimonials.title": "Real mijozlar fikri va showroom taassurotlari",
    "contact.eyebrow": "Lead form",
    "contact.title": "Mebelingizni tanlash uchun 1 daqiqada bog'laning",
    "contact.text": "Qaysi model qiziqtirayotganini yozing - menejerimiz tezkor javob beradi, showroom vaqtini belgilaydi yoki Telegram orqali katalog yuboradi.",
    "form.name": "Ism",
    "form.phone": "Telefon",
    "form.product": "Qaysi mebel qiziqtiryapti",
    "form.select": "Tanlang",
    "form.message": "Xabar",
    "form.submit": "So'rov yuborish",
    "ui.view": "Ko'rish",
    "ui.order": "Buyurtma berish",
    "ui.map": "Xaritada",
    "ui.visit": "Tashrif buyurish",
    "ui.showroom": "Showroom",
    "footer.text": "Premium mebel, showroom tajribasi va tezkor aloqa bir sahifada jamlangan konversiya-focused landing.",
    "footer.links": "Linklar",
    "footer.contact": "Kontakt",
    "footer.privacy": "Maxfiylik siyosati",
  },
  ru: {
    "menu.home": "Главная",
    "menu.categories": "Категории",
    "menu.bestsellers": "Бестселлеры",
    "menu.collection": "Новая коллекция",
    "menu.promo": "Акции",
    "menu.about": "О бренде",
    "menu.showrooms": "Шоурумы",
    "menu.contact": "Контакты",
    "cta.catalog": "Смотреть каталог",
    "cta.catalogShort": "Каталог",
    "cta.manager": "Связаться с менеджером",
    "hero.eyebrow": "Премиальный showroom experience",
    "hero.title": "Элегантные мебельные коллекции для вашего интерьера",
    "hero.text": "Выбирайте премиальные диваны, кровати и дизайнерские решения для каждой комнаты вместе с KUKA HOME.",
    "hero.stat1": "лет опыта",
    "hero.stat2": "рейтинг клиентов",
    "hero.stat3": "счастливых заказов",
    "hero.label": "2026 Signature Collection",
    "hero.badge": "Персональный подбор + консультация в шоуруме",
    "benefits.eyebrow": "Почему KUKA HOME",
    "benefits.title": "Премиальный продукт и сервис в одном пространстве",
    "categories.eyebrow": "Каталог",
    "categories.title": "Подборки для каждой зоны дома",
    "categories.cta": "Смотреть все",
    "products.eyebrow": "Самые популярные",
    "products.title": "Бестселлеры и быстрый путь к заказу",
    "featured.eyebrow": "New collection",
    "featured.title": "Новая коллекция в редакционном стиле",
    "featured.text": "Мягкие текстуры, глубокая цветовая палитра и современные силуэты.",
    "featured.cta": "Запросить коллекцию",
    "promo.eyebrow": "Ограниченное предложение",
    "promo.title": "Рамадан акция на избранные модели",
    "promo.text": "Посетите шоурум или свяжитесь с менеджером, чтобы получить персональное предложение.",
    "promo.days": "Дней",
    "promo.hours": "Часов",
    "promo.minutes": "Минут",
    "promo.cta": "Успеть на акцию",
    "showroom.eyebrow": "Оффлайн опыт",
    "showroom.title": "Посетите наши шоурумы и оцените коллекцию вживую",
    "about.eyebrow": "История бренда",
    "about.title": "KUKA HOME - премиальная точка встречи качества, эстетики и сервиса",
    "about.text1": "Мы подбираем мебель, которая усиливает интерьер, служит долго и дарит повседневный комфорт.",
    "about.text2": "Индивидуальная консультация, гибкие предложения и поддержка после покупки делают нас надежным партнером.",
    "about.point1": "материалы и отделка",
    "about.point2": "консультация и сервис",
    "about.point3": "связь и заказ",
    "testimonials.eyebrow": "Доверие клиентов",
    "testimonials.title": "Отзывы реальных клиентов и впечатления от шоурума",
    "contact.eyebrow": "Lead form",
    "contact.title": "Свяжитесь с нами за 1 минуту для подбора мебели",
    "contact.text": "Напишите, какая модель вас интересует, и менеджер быстро ответит удобным способом.",
    "form.name": "Имя",
    "form.phone": "Телефон",
    "form.product": "Какая мебель интересует",
    "form.select": "Выберите",
    "form.message": "Сообщение",
    "form.submit": "Отправить запрос",
    "ui.view": "Смотреть",
    "ui.order": "Заказать",
    "ui.map": "На карте",
    "ui.visit": "Посетить",
    "ui.showroom": "Шоурум",
    "footer.text": "Премиальная мебель, showroom experience и быстрые лиды на одной странице.",
    "footer.links": "Ссылки",
    "footer.contact": "Контакты",
    "footer.privacy": "Политика конфиденциальности",
  },
  en: {
    "menu.home": "Home",
    "menu.categories": "Categories",
    "menu.bestsellers": "Best sellers",
    "menu.collection": "New collection",
    "menu.promo": "Offers",
    "menu.about": "About",
    "menu.showrooms": "Showrooms",
    "menu.contact": "Contact",
    "cta.catalog": "View catalog",
    "cta.catalogShort": "Catalog",
    "cta.manager": "Talk to manager",
    "hero.eyebrow": "Premium showroom experience",
    "hero.title": "Elegant furniture collections designed for refined interiors",
    "hero.text": "Discover premium sofas, beds and designer solutions for every room with KUKA HOME.",
    "hero.stat1": "years of experience",
    "hero.stat2": "customer rating",
    "hero.stat3": "happy orders",
    "hero.label": "2026 Signature Collection",
    "hero.badge": "Personal selection + showroom consultation",
    "benefits.eyebrow": "Why KUKA HOME",
    "benefits.title": "A premium product and service approach in one destination",
    "categories.eyebrow": "Catalog directions",
    "categories.title": "Premium collections curated for every space",
    "categories.cta": "View all",
    "products.eyebrow": "Most chosen pieces",
    "products.title": "Best sellers with a fast path to order",
    "featured.eyebrow": "New collection",
    "featured.title": "Editorial living spaces from the newest collection",
    "featured.text": "Soft textures, deep color balance and contemporary silhouettes.",
    "featured.cta": "Request collection",
    "promo.eyebrow": "Limited offer",
    "promo.title": "Ramadan premium offer for selected models",
    "promo.text": "Visit the showroom or contact a manager for a tailored discount and delivery terms.",
    "promo.days": "Days",
    "promo.hours": "Hours",
    "promo.minutes": "Minutes",
    "promo.cta": "Claim the offer",
    "showroom.eyebrow": "Offline experience",
    "showroom.title": "Visit our showrooms and experience the collection in person",
    "about.eyebrow": "Brand story",
    "about.title": "KUKA HOME blends quality, aesthetics and service into one premium destination",
    "about.text1": "We curate furniture that elevates interiors, lasts longer and improves daily comfort.",
    "about.text2": "Close consultation, tailored offers and post-sale support make KUKA HOME more than a furniture store.",
    "about.point1": "materials and finish",
    "about.point2": "consultation and service",
    "about.point3": "speed of contact",
    "testimonials.eyebrow": "Customer trust",
    "testimonials.title": "Real client feedback and showroom impressions",
    "contact.eyebrow": "Lead form",
    "contact.title": "Connect in one minute to choose your next furniture piece",
    "contact.text": "Tell us what you need and our manager will reply quickly with a catalog, visit time or tailored offer.",
    "form.name": "Name",
    "form.phone": "Phone",
    "form.product": "Interested furniture",
    "form.select": "Select",
    "form.message": "Message",
    "form.submit": "Send request",
    "ui.view": "View",
    "ui.order": "Order now",
    "ui.map": "Open map",
    "ui.visit": "Book visit",
    "ui.showroom": "Showroom",
    "footer.text": "Premium furniture, showroom experience and conversion-focused contact paths on one page.",
    "footer.links": "Links",
    "footer.contact": "Contact",
    "footer.privacy": "Privacy policy",
  },
};
